"""remove comment, upd user

Revision ID: 09957e1ea028
Revises: 852317eb3bec
Create Date: 2025-04-21 23:24:22.288870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09957e1ea028'
down_revision: Union[str, None] = '852317eb3bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_comments')
    op.drop_column('users', 'is_block')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_block', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('review_comments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('review_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name='review_comments_review_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='review_comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='review_comments_pkey')
    )
    # ### end Alembic commands ###
